version: '3.8'
services:
  localstack:
    image: localstack/localstack-pro:4.5
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LS_TOKEN}
      - SERVICES=dynamodb,apigateway,cognito-idp,cognito-identity,lambda,logs,events,cloudwatch,ssm,cloudformation,iam,s3,ecr
      - DEBUG=1
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=1
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SKIP_SSL_CERT_DOWNLOAD=1
      - LAMBDA_IGNORE_ARCHITECTURE=1
      - LEGACY_DIRECTORIES=1
      - FORCE_DEFAULT_XML_RESPONSE=1
      - DISABLE_CORS_CHECKS=1
      - DISABLE_EVENTS=1
      - EDGE_BIND_HOST=0.0.0.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack-data:/var/lib/localstack           # persist stuff in a local folder
